apiVersion: v1
kind: Service
metadata:
  labels:
    app: net-inventory
  name: netinv-db
spec:
  ports:
    - port: 5432
  selector:
    app: net-inventory
    tier: netinv-db

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: netinv-db
  labels:
spec:
  replicas: 1
  selector:
    matchLabels:
      app: net-inventory
      tier: netinv-db
  template:
    metadata:
      labels:
        app: net-inventory
        tier: netinv-db
    spec:
      containers:
      - env:
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
        - name: POSTGRES_DB
        #  value: net_inventory
          valueFrom:
            secretKeyRef:
            name: net-inventory
            key: postgres-db
        - name: POSTGRES_PASSWORD
          #value: Cisco123
          valueFrom:
            secretKeyRef:
            name: net-inventory
            key: postgres-password
        - name: POSTGRES_USER
         # value: root
          valueFrom:
            secretKeyRef:
            name: net-inventory
            key: postgres-user
        image: cisco-devops/net_inventory/net_inventory_db:master
        name: netinv-db
        ports:
        - containerPort: 5432
      restartPolicy: Always
